{
    "Pairings": [
        {
            "TotalDutyCost": 0,
            "TotalDutyLengthinMin": 0,
            "PairingLastSyncDate": null,
            "ReservationLastSyncDate": null,
            "IropLastSyncDate": null,
            "ShowGMTTime": false,
            "ScheduleList": [
                {
                    "ScheduledDate": "2023-03-06T00:00:00",
                    "BlockTime": "",
                    "Credit": "",
                    "TAFB": "",
                    "PairingNumber": "CR20230306D| CR20230306A",
                    "PairingNumberDisplay": null,
                    "Legs": [
                        {
                            "SegmentSequenceNumber": 0,
                            "AirlineCode": null,
                            "FlightNumber": null,
                            "Origin": null,
                            "Destination": null,
                            "ScheduledArrivalTime": "0001-01-01T00:00:00",
                            "ScheduledDepartureTime": "0001-01-01T00:00:00",
                            "EstimatedArrivalTime": null,
                            "EstimatedDepartureTime": null,
                            "ActualArrivalTime": null,
                            "ActualDepartureTime": null,
                            "Crews": null,
                            "Reservation": [
                                {
                                    "CzReservationId": 72920,
                                    "ReservationId": 4498900104,
                                    "TransactionId": "CRBOM1101202303061700",
                                    "TransporterName": "Mumbai Transport",
                                    "HotelName": "",
                                    "HotelAddress": "",
                                    "TripType": 6,
                                    "CheckInTime": "2023-03-06T17:20:00",
                                    "CheckOutTime": "2023-03-06T15:50:00",
                                    "CalcCheckintimeLocal": "2023-03-06T17:20:00",
                                    "CalcCheckouttimeLocal": "2023-03-06T15:50:00",
                                    "ReservationDate": "2023-03-06T15:50:00",
                                    "AirportCode": "BOM",
                                    "PickupTime": "2023-03-06T15:50:00",
                                    "PickupTimeLocal": "2023-03-06T15:50:00",
                                    "Dropofftime": "2023-03-06T17:20:00",
                                    "DropofftimeLocal": "2023-03-06T17:20:00",
                                    "ReservationStartDate": "2023-03-06T17:00:00",
                                    "ReservationEndDate": "2023-03-06T17:00:00",
                                    "ReservationStatus": "Schedule",
                                    "IsCancelledReservation": false,
                                    "TransporterId": 5925,
                                    "TripId": 44989001041,
                                    "CzHotelId": 0,
                                    "HotelId": 0,
                                    "HotelKey": 0,
                                    "TransportCrews": null,
                                    "SameHotelCrews": null,
                                    "PreviousDayReservation": false,
                                    "CzReservationSequence": 1,
                                    "IsTop": false,
                                    "ShowTransport": 1,
                                    "ShowHotel": 0,
                                    "ShowHome": 0,
                                    "OnlyFlightNumber": "1101",
                                    "DataTypeId": 0,
                                    "HotelReservation": "",
                                    "ConnectedFlightNumber": "CRA",
                                    "ConnectedAirportCode": "",
                                    "IsScheduleGMTDate": 0,
                                    "HotelStayNight": "",
                                    "TransportationType": 2,
                                    "PickupLocation": "20, Adi Murzban Path 20, Adi Murzban Path, Borabazar Precinct, Ballard Estate, Fort, Mumbai, Maharashtra 400001, India",
                                    "DropOffLocation": "BOM",
                                    "DropOffHotelId": 0,
                                    "DropOffHotelKey": 0,
                                    "DropOffHotelName": "",
                                    "DropOffHotelAddress": ""
                                }
                            ],
                            "LegId": 0,
                            "CzSegmentSequenceNumber": 1,
                            "DataTypeId": 0,
                            "ScheduledDepartureTimeLocal": null,
                            "ScheduledArrivalTimeLocal": null,
                            "ScheduledDepartureTimeGMTOffset": null,
                            "ScheduledArrivalTimeGMTOffset": null,
                            "IsLeg": 0
                        },
                        {
                            "SegmentSequenceNumber": 0,
                            "AirlineCode": null,
                            "FlightNumber": null,
                            "Origin": null,
                            "Destination": null,
                            "ScheduledArrivalTime": "0001-01-01T00:00:00",
                            "ScheduledDepartureTime": "0001-01-01T00:00:00",
                            "EstimatedArrivalTime": null,
                            "EstimatedDepartureTime": null,
                            "ActualArrivalTime": null,
                            "ActualDepartureTime": null,
                            "Crews": null,
                            "Reservation": [
                                {
                                    "CzReservationId": 72921,
                                    "ReservationId": 4498900105,
                                    "TransactionId": "CRBOM2204202303062000",
                                    "TransporterName": "Mumbai Transport",
                                    "HotelName": "",
                                    "HotelAddress": "",
                                    "TripType": 5,
                                    "CheckInTime": "2023-03-06T22:40:00",
                                    "CheckOutTime": "2023-03-06T22:40:00",
                                    "CalcCheckintimeLocal": "2023-03-06T22:40:00",
                                    "CalcCheckouttimeLocal": "2023-03-06T22:40:00",
                                    "ReservationDate": "2023-03-06T21:10:00",
                                    "AirportCode": "BOM",
                                    "PickupTime": "2023-03-06T21:10:00",
                                    "PickupTimeLocal": "2023-03-06T21:10:00",
                                    "Dropofftime": "2023-03-06T22:40:00",
                                    "DropofftimeLocal": "2023-03-06T22:40:00",
                                    "ReservationStartDate": "2023-03-06T20:00:00",
                                    "ReservationEndDate": "2023-03-06T20:00:00",
                                    "ReservationStatus": "Schedule",
                                    "IsCancelledReservation": false,
                                    "TransporterId": 5925,
                                    "TripId": 44989001051,
                                    "CzHotelId": 0,
                                    "HotelId": 0,
                                    "HotelKey": 0,
                                    "TransportCrews": null,
                                    "SameHotelCrews": null,
                                    "PreviousDayReservation": false,
                                    "CzReservationSequence": 2,
                                    "IsTop": false,
                                    "ShowTransport": 1,
                                    "ShowHotel": 0,
                                    "ShowHome": 0,
                                    "OnlyFlightNumber": "2204",
                                    "DataTypeId": 0,
                                    "HotelReservation": "",
                                    "ConnectedFlightNumber": "CRA",
                                    "ConnectedAirportCode": "",
                                    "IsScheduleGMTDate": 0,
                                    "HotelStayNight": "",
                                    "TransportationType": 2,
                                    "PickupLocation": "BOM",
                                    "DropOffLocation": "20, Adi Murzban Path 20, Adi Murzban Path, Borabazar Precinct, Ballard Estate, Fort, Mumbai, Maharashtra 400001, India",
                                    "DropOffHotelId": 0,
                                    "DropOffHotelKey": 0,
                                    "DropOffHotelName": "",
                                    "DropOffHotelAddress": ""
                                }
                            ],
                            "LegId": 0,
                            "CzSegmentSequenceNumber": 2,
                            "DataTypeId": 0,
                            "ScheduledDepartureTimeLocal": null,
                            "ScheduledArrivalTimeLocal": null,
                            "ScheduledDepartureTimeGMTOffset": null,
                            "ScheduledArrivalTimeGMTOffset": null,
                            "IsLeg": 0
                        }
                    ],
                    "IsScheduleGMTDate": 0
                }
            ]
        }
    ]
}